# Generated by Django 2.1.5 on 2020-07-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mieter', '0003_auto_20200727_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mieterperson',
            name='eid_versicherung',
            field=models.BooleanField(blank=True, choices=[(None, 'N/A'), (True, 'Yes'), (False, 'No')], default=None, null=True, verbose_name='In den letzten fünf Jahren habe ich eine eidesstattliche Versicherung abgegeben'),
        ),
        migrations.AlterField(
            model_name='mieterperson',
            name='eid_versicherung_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mieterperson',
            name='gewerbliche_nutzung',
            field=models.BooleanField(blank=True, choices=[(None, 'N/A'), (True, 'Yes'), (False, 'No')], default=None, null=True, verbose_name='Ist einge gewerbliche Nutzung der Wohnung beabsichtigt?'),
        ),
        migrations.AlterField(
            model_name='mieterperson',
            name='gewerbliche_nutzung_zweck',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Zweck angeben'),
        ),
        migrations.AlterField(
            model_name='mieterperson',
            name='insolvenzverfahren',
            field=models.BooleanField(blank=True, choices=[(None, 'N/A'), (True, 'Yes'), (False, 'No')], default=None, null=True, verbose_name='In den letzten fünf Jahren wurde ein Insolvenzverfahren gegen mich eröffnet'),
        ),
        migrations.AlterField(
            model_name='mieterperson',
            name='insolvenzverfahren_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mieterperson',
            name='raeumungsklage',
            field=models.BooleanField(blank=True, choices=[(None, 'N/A'), (True, 'Yes'), (False, 'No')], default=None, null=True, verbose_name='In den letzten fünf Jahren wurde Räumungsklage gegen mich erhoben'),
        ),
        migrations.AlterField(
            model_name='mieterperson',
            name='raeumungsklage_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mieterperson',
            name='sozialleistungen',
            field=models.BooleanField(blank=True, choices=[(None, 'N/A'), (True, 'Yes'), (False, 'No')], default=None, null=True, verbose_name='Ich beziehe Sozialleistungen zur Zahlung der Miete / Kaution'),
        ),
        migrations.AlterField(
            model_name='mieterperson',
            name='sozialleistungen_beschreibung',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Welche und in welchem Umfang'),
        ),
        migrations.AlterField(
            model_name='mieterperson',
            name='tierhaltung',
            field=models.BooleanField(blank=True, choices=[(None, 'N/A'), (True, 'Yes'), (False, 'No')], default=None, null=True, verbose_name='Tierhaltung beabsichtigt'),
        ),
        migrations.AlterField(
            model_name='mieterperson',
            name='tierhaltung_beschreibung',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Tierart / Rasse'),
        ),
        migrations.AlterField(
            model_name='mieterperson',
            name='vorstrafen',
            field=models.BooleanField(blank=True, choices=[(None, 'N/A'), (True, 'Yes'), (False, 'No')], default=None, null=True, verbose_name='Vorstrafen / Haftbefehl'),
        ),
        migrations.AlterField(
            model_name='mieterperson',
            name='vorstrafen_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mieterperson',
            name='zwangsvollstraeckung',
            field=models.BooleanField(blank=True, choices=[(None, 'N/A'), (True, 'Yes'), (False, 'No')], default=None, null=True, verbose_name='In den letzten fünf Jahren wurde Zwangsvollstreckung gegen mich eingeleitet'),
        ),
        migrations.AlterField(
            model_name='mieterperson',
            name='zwangsvollstraeckung_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
