# Generated by Django 2.1.5 on 2020-07-28 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mieter', '0004_auto_20200727_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familienstand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familienstand', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MieterpersonFamilienstand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familienstand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mieter.Familienstand')),
                ('mieterperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mieter.Mieterperson')),
            ],
        ),
    ]
