# Generated by Django 2.1.5 on 2020-07-29 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mieter', '0008_auto_20200729_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='location',
            new_name='file',
        ),
    ]
