# Generated by Django 2.1.5 on 2020-07-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mieter', '0009_auto_20200729_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wunschwohnung',
            name='aktiv',
            field=models.BooleanField(blank=True, choices=[(None, 'N/A'), (True, 'Yes'), (False, 'No')], default=None, null=True, verbose_name='Gibt an, ob Gesuch aktiv ist'),
        ),
    ]
