# Generated by Django 3.0.8 on 2020-08-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mieter', '0010_auto_20200730_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nebenmieter',
            name='geburtsdatum',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nebenmieter',
            name='nachname',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nebenmieter',
            name='vorname',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
