# Generated by Django 3.0.8 on 2020-08-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mieter', '0011_auto_20200802_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wunschwohnung',
            name='anzahl_zimmer',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Anzahl der Zimmer ab'),
        ),
        migrations.AlterField(
            model_name='wunschwohnung',
            name='bezugsfertig',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Bezugsfertig ab'),
        ),
        migrations.AlterField(
            model_name='wunschwohnung',
            name='flaeche',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Wohnfläche ab'),
        ),
        migrations.AlterField(
            model_name='wunschwohnung',
            name='max_miete',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Maximale Kaltmiete pro Monat'),
        ),
    ]
