# Generated by Django 3.0.8 on 2020-08-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mieter', '0012_auto_20200802_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wunschwohnung',
            name='land',
            field=models.CharField(blank=True, default='Deutschland', max_length=50, null=True, verbose_name='Land'),
        ),
        migrations.AlterField(
            model_name='wunschwohnung',
            name='stadt',
            field=models.CharField(blank=True, default='München', max_length=50, null=True, verbose_name='Stadt'),
        ),
    ]
