# Generated by Django 3.0.8 on 2020-08-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mieter', '0013_auto_20200802_0354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
    ]
