# Generated by Django 3.0.8 on 2020-08-01 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mieter', '0015_documentstype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='doc_type',
        ),
    ]
