# Generated by Django 3.0.8 on 2020-08-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mieter', '0017_auto_20200804_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wunschwohnung',
            name='aktiv',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Gibt an, ob Gesuch aktiv ist'),
        ),
    ]
